export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST'

export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS'

export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE'

export const DELETE_INVOICE = 'DELETE_INVOICE'

export const DELETE_ALL_INVOICES = 'DELETE_ALL_INVOICES'